services:
  - type: web
    name: replquick-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: REDIS_URL
        fromDatabase:
          name: replquick-redis
          property: connectionString
    nodeVersion: 20.x
    healthCheckPath: /eval
    autoDeploy: true

  - type: web
    name: replquick-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://replquick-backend.onrender.com

databases:
  - name: replquick-redis
    databaseName: replquick
    plan: free